# docker build -f Dockerfile_transcribe_audio -t jacobloe/transcribe_audio:0.1 .
# docker run --rm -it -v $(pwd)/../videos/:/video:ro -v $(pwd)/static/features_videos/:/data jacobloe/transcribe_audio:0.1 /video /data
FROM python:3.7

ENV DEBIAN_FRONTEND noninteractive

COPY requirements_transcribe_audio.txt /root

RUN pip install --trusted-host pypi.python.org -r /root/requirements_transcribe_audio.txt
RUN apt-get update && apt-get install -y ffmpeg #apt-get install -y vim

RUN curl -LO https://github.com/mozilla/DeepSpeech/releases/download/v0.7.4/deepspeech-0.7.4-models.pbmm
RUN curl -LO https://github.com/mozilla/DeepSpeech/releases/download/v0.7.4/deepspeech-0.7.4-models.scorer

COPY transcribe_audio.py /root

VOLUME "/video"
VOLUME "/data"

WORKDIR /root

ENTRYPOINT ["python3", "transcribe_audio.py"]